# Generated by Django 2.2.1 on 2019-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=10, unique=True)),
                ('viber', models.CharField(blank=True, max_length=10, unique=True)),
                ('sms', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
