# Generated by Django 2.2.1 on 2019-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='sms',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='viber',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
