# Generated by Django 2.2.1 on 2019-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
                ('at', models.CharField(blank=True, max_length=10)),
                ('volume', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
