# Generated by Django 2.2.1 on 2019-05-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190507_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='post_director',
        ),
        migrations.AddField(
            model_name='company',
            name='last_name_director',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия директора '),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес '),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН '),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, max_length=50, verbose_name='КПП '),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_director',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя директора '),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ОГРН '),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон '),
        ),
        migrations.AlterField(
            model_name='company',
            name='post_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Юридический адрес '),
        ),
    ]
